[tool.poetry]
name = "electronic store"
version = "0.1.0"
description = ""
authors = ["GeorgijP <georgij.puzanov@inbox.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
